In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:

df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [8]:
X_train

age  gender  fever   cough       city
13   64    Male  102.0    Mild  Bangalore
57   49  Female   99.0  Strong  Bangalore
4    65  Female  101.0    Mild     Mumbai
76   80    Male  100.0    Mild  Bangalore
29   34  Female    NaN  Strong     Mumbai
..  ...     ...    ...     ...        ...
3    31  Female   98.0    Mild    Kolkata
87   47    Male  101.0  Strong  Bangalore
43   22  Female   99.0    Mild  Bangalore
48   66    Male   99.0  Strong  Bangalore
50   19    Male  101.0    Mild      Delhi

[80 rows x 5 columns]

In [ ]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [ ]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [29]:
X_train_cough

array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],

In [20]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [30]:
X_train_gender_city

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],


In [21]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [22]:
X_train_age

array([[64],
       [49],
       [65],
       [80],
       [34],
       [68],
       [83],
       [ 5],
       [64],
       [10],
       [73],
       [82],
       [11],
       [83],
       [25],
       [10],
       [56],
       [26],
       [38],
       [60],
       [14],
       [82],
       [51],
       [81],
       [51],
       [83],
       [69],
       [12],
       [23],
       [65],
       [49],
       [71],
       [54],
       [72],
       [79],
       [16],
       [59],
       [13],
       [65],
       [27],
       [33],
       [24],
       [27],
       [65],
       [27],
       [81],
       [69],
       [17],
       [46],
       [34],
       [14],
       [ 5],
       [20],
       [42],
       [82],
       [40],
       [47],
       [19],
       [70],
       [19],
       [73],
       [69],
       [64],
       [74],
       [20],
       [ 8],
       [12],
       [34],
       [42],
       [25],
       [20],
       [42],
       [16],
       [38],
       [84],
       [31],
       [47],

In [23]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [31]:
X_train_transformed

array([[ 64.  , 102.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [ 49.  ,  99.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ],
       [ 65.  , 101.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ],
       [ 80.  , 100.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [ 34.  , 100.75,   0.  ,   0.  ,   0.  ,   1.  ,   1.  ],
       [ 68.  , 101.  ,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ],
       [ 83.  , 101.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ],
       [  5.  , 102.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ],
       [ 64.  ,  98.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [ 10.  ,  98.  ,   0.  ,   0.  ,   1.  ,   0.  ,   1.  ],
       [ 73.  , 103.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ],
       [ 82.  , 100.75,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ],
       [ 11.  , 100.  ,   0.  ,   0.  ,   1.  ,   0.  ,   1.  ],
       [ 83.  ,  98.  ,   1.  ,   1.  ,   0.  ,   0.  ,   0.  ],
       [ 25.  ,  99.  ,   0.  ,   0.  ,   1.  ,   0.  ,   1.  ],
       [ 10.  , 100.  ,  

## Mentos Jindagi

In [ ]:

from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

#Explanation
# This ColumnTransformer applies different preprocessing steps to different columns of the dataset:
# 1. **SimpleImputer** is applied to the 'fever' column to fill in any missing values.
# 2. **OrdinalEncoder** is applied to the 'cough' column, with specified categories 'Mild' and 'Strong'.
# 3. **OneHotEncoder** is applied to the 'gender' and 'city' columns, converting them into a one-hot encoded format while dropping the first category to avoid dummy variable trap.
# 4. The `remainder='passthrough'` argument ensures that any columns not specified in the transformers are passed through without changes.


In [32]:
train_transformed = transformer.fit_transform(X_train)

In [33]:
train_transformed

array([[102.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  64.  ],
       [ 99.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,  49.  ],
       [101.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,  65.  ],
       [100.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  80.  ],
       [100.75,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,  34.  ],
       [101.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,  68.  ],
       [101.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,  83.  ],
       [102.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,   5.  ],
       [ 98.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  64.  ],
       [ 98.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  10.  ],
       [103.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,  73.  ],
       [100.75,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,  82.  ],
       [100.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  11.  ],
       [ 98.  ,   0.  ,   1.  ,   1.  ,   0.  ,   0.  ,  83.  ],
       [ 99.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  25.  ],
       [100.  ,   0.  ,  

In [28]:

transformer.transform(X_test).shape

(20, 7)