In [51]:
#Import XGBOOST
import xgboost as xgb

In [52]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.datasets import load_digits

In [53]:
X, y = load_digits(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [54]:
#Import Gradinet Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier()

In [55]:
import time 
start_time = time.time()
#Fit the model
model.fit(X_train, y_train)
end_time = time.time()
training_time = end_time - start_time
print(f"Training Time: {training_time} seconds")

Training Time: 3.897538900375366 seconds


In [56]:
#Fitting xgboost model
model1 = XGBClassifier(n_jobs=4)
start = time.time()
model1.fit(X_train, y_train)
end = time.time()
fit_time = end - start
print(f"Model fitting time: {fit_time} seconds")

Model fitting time: 0.31072497367858887 seconds


In [60]:
#Comparing accuracy
y_pred = model1.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: of XGBClassifier is {accuracy}")
print("confusion_matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy: of XGBClassifier is 0.9694444444444444
confusion_matrix
[[32  0  0  0  1  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  1  0]
 [ 0  1  0  0 45  0  0  0  0  0]
 [ 0  0  0  0  0 46  1  0  0  0]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  1  0  0  0  1  0  0 28  0]
 [ 0  0  0  0  0  0  0  1  1 38]]


In [59]:
#Comparing accuracy
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: of Gradient Boosting Classifier is {accuracy}")
print("confusion_matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy: of Gradient Boosting Classifier is 0.9694444444444444
confusion_matrix
[[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 32  0  0  0  0  1  0  0]
 [ 0  1  0 32  0  0  0  0  1  0]
 [ 0  1  0  0 44  0  0  1  0  0]
 [ 0  0  0  0  0 46  1  0  0  0]
 [ 0  0  0  0  0  1 33  0  1  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  0  0  0  0  0  0  0 30  0]
 [ 0  0  0  0  0  0  0  1  1 38]]


In [62]:
#Percentage improvement in time
time_improvement = ((training_time - fit_time) / training_time) * 100
print(f"Percentage improvement in training time when using XGBClassifier is {time_improvement}%")

Percentage improvement in training time when using XGBClassifier is 92.02766202927023%


In [ ]:
#Let's use GPU to train XGBoost model
model_gpu = XGBClassifier(n_jobs=4,device='cuda')
start_gpu = time.time()
model_gpu.fit(X_train, y_train)
end_gpu = time.time()
fit_time_gpu = end_gpu - start_gpu
print(f"Model fitting time using GPU: {fit_time_gpu} seconds")

/Users/ankitpokhrel/Downloads/All_projects/ML_Projects/myenv/lib/python3.12/site-packages/xgboost/training.py:199: UserWarning: [22:17:57] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  bst.update(dtrain, iteration=i, fobj=obj)


Model fitting time using GPU: 0.36162519454956055 seconds


## Handeling Missing Data

In [68]:
#Handling missing values with XGBoost, X contains two missing values and other values is just multiple of 2 as 0 and multiple of 3 as 1
X = np.array([[2, 4, np.nan], [6, np.nan, 12], [14, 16, 18], [20, 22, 24], [3, 6, np.nan], [9, np.nan, 15], [21, 24, 27], [30, 33, 36]])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
model_missing = XGBClassifier(n_jobs=4)
model_missing.fit(X_train, y_train)
y_pred_missing = model_missing.predict(X_test)
accuracy_missing = accuracy_score(y_test, y_pred_missing)
print(f"Accuracy with missing values handled by XGBoost: {accuracy_missing}")

Accuracy with missing values handled by XGBoost: 0.5
