### Numpy Basics to Advance

In [2]:
import numpy as np
a = np.array((1,2,3,4))
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
#2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
a = np.arange(1,11).reshape(5,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.random.random((3,4))

array([[0.06535337, 0.43439932, 0.9891856 , 0.53086531],
       [0.90357362, 0.02913286, 0.03750276, 0.98355901],
       [0.71801723, 0.41493761, 0.42683609, 0.00587218]])

In [9]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
#Attributes
a1 = np.arange(1)
a2 = np.arange(12,dtype = float).reshape(6,2)
a3 = np.arange(16).reshape(2,2,4)

In [12]:
a2.ndim

2

In [13]:
a1.dtype

dtype('int64')

In [14]:
a3.size

8

In [23]:
a3.size

16

In [19]:
a3.shape

(2, 2, 2)

In [34]:
a1 = np.arange(100,dtype = float)
a1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [35]:
a1.size

100

In [38]:
a3.dtype

dtype('int64')

In [44]:
a4 = a3.astype(np.int32)
a4.dtype

dtype('int32')

In [45]:
a4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]], dtype=int32)

In [46]:
#Array operation
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [50]:
#Arithmetic operations
print(a1)
print(a1*2)
print(a1/2)
print(a1-2)
print(a1+2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [60]:
#Relational operations
a2 > 12

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
#Vector operations
a3 = a1/a2
a3

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [75]:
#Array Functions
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[88., 80., 33.],
       [19., 33., 89.],
       [21., 23., 23.]])

In [71]:
np.max(a1)

np.float64(94.0)

In [77]:
np.min(a1)

np.float64(19.0)

In [82]:
np.max(a1,axis=0)

array([88., 80., 89.])

In [80]:
a1

array([[88., 80., 33.],
       [19., 33., 89.],
       [21., 23., 23.]])

In [83]:
#Dot product
a1 = np.arange(4,12).reshape(2,4)
a2 = np.arange(12,20).reshape(4,2)

In [88]:
np.dot(a1,a2)

array([[340, 362],
       [580, 618]])

In [94]:
a2 = a1 * 0.24342334
a2

array([[0.97369336, 1.2171167 , 1.46054004, 1.70396338],
       [1.94738672, 2.19081006, 2.4342334 , 2.67765674]])

In [92]:
np.round(a2)

array([[1., 1., 1., 2.],
       [2., 2., 2., 3.]])

In [93]:
np.ceil(a2)

array([[1., 2., 2., 2.],
       [2., 3., 3., 3.]])

In [95]:
np.floor(a2)

array([[0., 1., 1., 1.],
       [1., 2., 2., 2.]])

In [100]:
a3 = np.array([1.5,1.6,1.9,1.55,1.75,1.45])

In [101]:
np.round(a3)

array([2., 2., 2., 2., 2., 1.])

In [102]:
np.ceil(a3)

array([2., 2., 2., 2., 2., 2.])

In [103]:
np.floor(a3)

array([1., 1., 1., 1., 1., 1.])

In [104]:
a1

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a1[0,3]

np.int64(7)

In [110]:
a3 = np.arange(12,24).reshape(2,3,2)

In [111]:
a3

array([[[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [112]:
#Let's capture 21
a3[1,1,1]

np.int64(21)

In [119]:
#Let's capture 23
newvar = a3[1,2,1]

In [129]:
a5 = np.arange(24,36).reshape(4,3)
a5

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [131]:
#Extracting first row
a5[0,:]

array([24, 25, 26])

In [132]:
#Extracting first column
a5[:,0]

array([24, 27, 30, 33])

In [ ]:
#Extracting third column
a5[:,2]

array([26, 29, 32, 35])

In [139]:
a5

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [140]:
#Extract [[31,32],[34,35]]
a5[2:,1:]

array([[31, 32],
       [34, 35]])

In [142]:
#Extract 24,30,26,32
a5[::2,::2]

array([[24, 26],
       [30, 32]])

In [144]:
a3 = np.arange(12).reshape(3,4)
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
#Extract 1,3,9,11
a3[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [149]:
a3[::3,0::2]

array([[0, 2]])

In [152]:
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
a3[1,::3]

array([4, 7])

In [168]:
a3[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [170]:
a4 = np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [172]:
#[[ 9, 10, 11],
# [12, 13, 14],
# [15, 16, 17]],

a4[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [174]:
a4[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [176]:
a4[0,1]

array([3, 4, 5])

In [177]:
a4[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [178]:
a4[::2,::3,::2]

array([[[ 0,  2]],

       [[18, 20]]])

In [187]:
#Iterating
for i in a4:
    for j in i:
        for k in j:
            print(k,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [ ]:
for i in np.nditer(a4):
    print(i,end = " ")
    

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [193]:
#Ravel to convert nd array into 1D
for i in a4.ravel():
    print(i,end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [5]:
import numpy as np
a = np.array([1,2])
b = np.array([5,6])
print(np.dot(a,b))

17


In [9]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])