
###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


In [62]:
import numpy as np
a = np.random.randint(0,100,12).reshape(3,4)

In [24]:
np.sort(a)[::-1]

array([[19, 52, 60, 75],
       [12, 39, 59, 96],
       [27, 39, 66, 81]])

In [25]:
np.sort(a,axis = 0)

array([[12, 19, 52, 27],
       [39, 39, 59, 60],
       [75, 66, 81, 96]])

See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [26]:
# code here

(np.sort(a.ravel())).reshape(3,4)



array([[12, 19, 27, 39],
       [39, 52, 59, 60],
       [66, 75, 81, 96]])

In [30]:
# a.ravel()
a.flatten()

array([39, 66, 81, 27, 12, 39, 59, 96, 75, 19, 52, 60])

In [31]:
a

array([[39, 66, 81, 27],
       [12, 39, 59, 96],
       [75, 19, 52, 60]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
# code here

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
# code here

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [66]:
# code here
print(a)
np.flip(a)

[[ 1  7 44 28]
 [43 95 61 99]
 [68 50 15 29]]


array([[29, 15, 50, 68],
       [99, 61, 95, 43],
       [28, 44,  7,  1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [ ]:
# code here


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [68]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [69]:
# code here
np.ravel(arr1)

array([0, 1, 2])

In [ ]:
np.ravel(arr1)

array([3, 4, 5, 6])

In [72]:
arr3.flatten()

array([7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [56]:
# code here
import numpy as np
# np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
# arr = arr.ravel()
maxi = np.argmax(arr)
mini = np.argmin(arr)
print(arr[0,maxi],arr[0,mini])
np.delete(arr,[maxi,mini])
arr


997 100


array([[400, 907, 893, 478, 777, 464, 336, 155, 747, 358, 901, 196, 491,
        279, 732, 311, 743, 583, 896, 974, 781, 704, 991, 781, 777, 763,
        519, 206, 474, 959, 629, 374, 417, 467, 484, 652, 406, 976, 253,
        336, 611, 453, 372, 468, 361, 465, 167, 858, 486, 548, 596, 582,
        717, 380, 405, 510, 807, 226, 635, 759, 814, 837, 881, 100, 829,
        197, 476, 712, 807, 163, 621, 258, 299, 623, 128, 672, 863, 662,
        371, 426, 848, 576, 691, 976, 353, 417, 104, 987, 842, 852, 480,
        863, 580, 787, 495, 742, 861, 868, 421, 367, 713, 642, 116, 101,
        883, 221, 462, 614, 654, 165, 943, 758, 831, 789, 880, 684, 252,
        845, 406, 695, 537, 745, 401, 533, 694, 367, 911, 979, 746, 158,
        934, 915, 687, 515, 770, 841, 778, 401, 127, 294, 777, 287, 747,
        490, 729, 993, 107, 292, 823, 158, 772, 600, 329, 232, 156, 659,
        597, 163, 638, 163, 572, 675, 432, 587, 687, 615, 204, 807, 956,
        997, 265, 188, 746, 605, 858, 437, 308, 235

In [60]:
a = np.arange(10,100)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
# code here

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [ ]:
# code here